create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  producto_id integer not null references public.productos(id),
  nombre varchar not null,
  precio numeric not null,
  cantidad integer not null check (cantidad > 0),
  subtotal numeric not null,
  creado_en timestamptz not null default now()
);

alter table public.order_items enable row level security;

create policy "Usuarios ven items de sus ordenes"
on public.order_items
for select
to public
using (
  exists (
    select 1
    from public.ordenes
    where ordenes.id = order_items.orden_id
      and ordenes.usuario_id = auth.uid()
  )
);

create index if not exists order_items_orden_id_idx
on public.order_items(orden_id);
