create table if not exists public.producto_variantes (
  id bigint generated by default as identity primary key,
  producto_id integer not null references public.productos(id) on delete cascade,
  nombre varchar(120) not null,
  color varchar(60),
  tamanio varchar(60),
  precio numeric not null check (precio >= 0),
  stock integer not null default 0 check (stock >= 0),
  imagen_url varchar(255),
  alt varchar(255),
  estado varchar(50) not null default 'Disponible',
  creado_en timestamptz not null default now()
);

create index if not exists producto_variantes_producto_id_idx
on public.producto_variantes(producto_id);

create unique index if not exists producto_variantes_unicas_idx
on public.producto_variantes(
  producto_id,
  coalesce(color, ''),
  coalesce(tamanio, '')
);

alter table public.producto_variantes enable row level security;

drop policy if exists "Todos pueden ver variantes" on public.producto_variantes;
drop policy if exists "Admins actualizan variantes" on public.producto_variantes;
drop policy if exists "Admins insertan variantes" on public.producto_variantes;
drop policy if exists "Admins eliminan variantes" on public.producto_variantes;

create policy "Todos pueden ver variantes"
on public.producto_variantes
for select
to public
using (true);

create policy "Admins actualizan variantes"
on public.producto_variantes
for update
to public
using (public.usuario_es_admin(auth.uid()))
with check (public.usuario_es_admin(auth.uid()));

create policy "Admins insertan variantes"
on public.producto_variantes
for insert
to public
with check (public.usuario_es_admin(auth.uid()));

create policy "Admins eliminan variantes"
on public.producto_variantes
for delete
to public
using (public.usuario_es_admin(auth.uid()));

alter table public.carrito
add column if not exists producto_variante_id bigint references public.producto_variantes(id);

alter table public.order_items
add column if not exists producto_variante_id bigint references public.producto_variantes(id),
add column if not exists variante_nombre varchar(120),
add column if not exists color varchar(60),
add column if not exists tamanio varchar(60),
add column if not exists imagen_url varchar(255);

alter table public.carrito
drop constraint if exists carrito_usuario_id_producto_id_key;

drop index if exists public.carrito_usuario_id_producto_id_key;
drop index if exists public.carrito_usuario_producto_base_unique;
drop index if exists public.carrito_usuario_producto_variante_unique;

create unique index carrito_usuario_producto_base_unique
on public.carrito(usuario_id, producto_id)
where producto_variante_id is null;

create unique index carrito_usuario_producto_variante_unique
on public.carrito(usuario_id, producto_variante_id)
where producto_variante_id is not null;

insert into public.producto_variantes (
  producto_id,
  nombre,
  color,
  precio,
  stock,
  imagen_url,
  alt
)
select p.id, v.nombre, v.color, v.precio, v.stock, v.imagen_url, v.alt
from public.productos p
cross join (
  values
    ('Verde', 'Verde', 26000::numeric, 8, '/macetaverde.jpg', 'Maceta clásica verde'),
    ('Gris', 'Gris', 28000::numeric, 7, '/macetagris.jpg', 'Maceta clásica gris'),
    ('Blanco', 'Blanco', 28000::numeric, 7, '/macetablanca.jpg', 'Maceta clásica blanca')
) as v(nombre, color, precio, stock, imagen_url, alt)
where p.nombre in ('Maceta clásica', 'Maceta clasica')
on conflict (producto_id, coalesce(color, ''), coalesce(tamanio, ''))
do update set
  nombre = excluded.nombre,
  precio = excluded.precio,
  stock = excluded.stock,
  imagen_url = excluded.imagen_url,
  alt = excluded.alt,
  estado = 'Disponible';

insert into public.producto_variantes (
  producto_id,
  nombre,
  color,
  tamanio,
  precio,
  stock,
  imagen_url,
  alt
)
select p.id, v.nombre, v.color, v.tamanio, v.precio, v.stock, v.imagen_url, v.alt
from public.productos p
cross join (
  values
    ('Negro chico', 'Negro', 'Chico', 24000::numeric, 6, '/macetanegra.jpg', 'Maceta minimal negra chica'),
    ('Negro mediano', 'Negro', 'Mediano', 31000::numeric, 6, '/macetanegra.jpg', 'Maceta minimal negra mediana'),
    ('Negro grande', 'Negro', 'Grande', 39000::numeric, 4, '/macetanegra.jpg', 'Maceta minimal negra grande'),
    ('Blanco chico', 'Blanco', 'Chico', 24000::numeric, 6, '/macetasset.jpg', 'Maceta minimal blanca chica'),
    ('Blanco mediano', 'Blanco', 'Mediano', 31000::numeric, 6, '/macetasset.jpg', 'Maceta minimal blanca mediana'),
    ('Blanco grande', 'Blanco', 'Grande', 39000::numeric, 4, '/macetasset.jpg', 'Maceta minimal blanca grande'),
    ('Gris chico', 'Gris', 'Chico', 25000::numeric, 5, '/macetasset.jpg', 'Maceta minimal gris chica'),
    ('Gris mediano', 'Gris', 'Mediano', 32000::numeric, 5, '/macetasset.jpg', 'Maceta minimal gris mediana'),
    ('Gris grande', 'Gris', 'Grande', 40500::numeric, 3, '/macetasset.jpg', 'Maceta minimal gris grande')
) as v(nombre, color, tamanio, precio, stock, imagen_url, alt)
where p.nombre = 'Maceta minimal'
on conflict (producto_id, coalesce(color, ''), coalesce(tamanio, ''))
do update set
  nombre = excluded.nombre,
  precio = excluded.precio,
  stock = excluded.stock,
  imagen_url = excluded.imagen_url,
  alt = excluded.alt,
  estado = 'Disponible';

create or replace function public.crear_orden_completa(
  p_usuario_id uuid,
  p_items jsonb,
  p_total numeric
)
returns table (
  orden_id bigint,
  success boolean,
  error_msg text
) as $$
declare
  v_orden_id bigint;
  v_item jsonb;
  v_producto record;
  v_variante record;
  v_producto_id integer;
  v_variante_id bigint;
  v_cantidad integer;
  v_precio numeric;
  v_total_calculado numeric := 0;
begin
  if p_usuario_id is null then
    raise exception 'Usuario inválido';
  end if;

  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'El carrito está vacío';
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_producto_id := (v_item ->> 'producto_id')::integer;
    v_variante_id := nullif(v_item ->> 'producto_variante_id', '')::bigint;
    v_cantidad := (v_item ->> 'cantidad')::integer;

    if v_producto_id is null or v_cantidad is null or v_cantidad <= 0 then
      raise exception 'Ítem inválido';
    end if;

    if v_variante_id is not null then
      select
        pv.id,
        pv.producto_id,
        pv.nombre,
        pv.color,
        pv.tamanio,
        pv.precio,
        pv.stock,
        pv.imagen_url,
        p.nombre as producto_nombre
      into v_variante
      from public.producto_variantes pv
      join public.productos p on p.id = pv.producto_id
      where pv.id = v_variante_id
        and pv.producto_id = v_producto_id
      for update of pv;

      if not found then
        raise exception 'Variante no encontrada';
      end if;

      if v_variante.stock < v_cantidad then
        raise exception 'Stock insuficiente para %', v_variante.nombre;
      end if;

      v_total_calculado := v_total_calculado + (v_variante.precio * v_cantidad);
    else
      select id, nombre, precio, stock
      into v_producto
      from public.productos
      where id = v_producto_id
      for update;

      if not found then
        raise exception 'Producto no encontrado';
      end if;

      if v_producto.stock < v_cantidad then
        raise exception 'Stock insuficiente para %', v_producto.nombre;
      end if;

      v_total_calculado := v_total_calculado + (v_producto.precio * v_cantidad);
    end if;
  end loop;

  if v_total_calculado <> p_total then
    raise exception 'Total inválido';
  end if;

  insert into public.ordenes (usuario_id, total, estado)
  values (p_usuario_id, v_total_calculado, 'pendiente')
  returning id into v_orden_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_producto_id := (v_item ->> 'producto_id')::integer;
    v_variante_id := nullif(v_item ->> 'producto_variante_id', '')::bigint;
    v_cantidad := (v_item ->> 'cantidad')::integer;

    if v_variante_id is not null then
      select
        pv.id,
        pv.producto_id,
        pv.nombre,
        pv.color,
        pv.tamanio,
        pv.precio,
        pv.stock,
        pv.imagen_url,
        p.nombre as producto_nombre
      into v_variante
      from public.producto_variantes pv
      join public.productos p on p.id = pv.producto_id
      where pv.id = v_variante_id
        and pv.producto_id = v_producto_id
      for update of pv;

      insert into public.order_items (
        orden_id,
        producto_id,
        producto_variante_id,
        nombre,
        variante_nombre,
        color,
        tamanio,
        precio,
        cantidad,
        subtotal,
        imagen_url
      )
      values (
        v_orden_id,
        v_variante.producto_id,
        v_variante.id,
        v_variante.producto_nombre,
        v_variante.nombre,
        v_variante.color,
        v_variante.tamanio,
        v_variante.precio,
        v_cantidad,
        v_variante.precio * v_cantidad,
        v_variante.imagen_url
      );

      update public.producto_variantes
      set stock = stock - v_cantidad
      where id = v_variante.id;
    else
      select id, nombre, precio, stock
      into v_producto
      from public.productos
      where id = v_producto_id
      for update;

      insert into public.order_items (
        orden_id,
        producto_id,
        nombre,
        precio,
        cantidad,
        subtotal
      )
      values (
        v_orden_id,
        v_producto.id,
        v_producto.nombre,
        v_producto.precio,
        v_cantidad,
        v_producto.precio * v_cantidad
      );

      update public.productos
      set stock = stock - v_cantidad
      where id = v_producto.id;
    end if;
  end loop;

  delete from public.carrito
  where usuario_id = p_usuario_id;

  return query select v_orden_id, true, null::text;
exception when others then
  return query select null::bigint, false, sqlerrm;
end;
$$ language plpgsql security definer set search_path = public;

grant execute on function public.crear_orden_completa(uuid, jsonb, numeric)
to authenticated, service_role;
